-- Create schema for user management
CREATE SCHEMA IF NOT EXISTS user_management;

-- Table for users
CREATE TABLE IF NOT EXISTS user_management.tb_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    state VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    public_identifier VARCHAR(100) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

INSERT INTO tb_user (name, email, state, city, public_identifier, active, created_at)
VALUES
  ('Admin User', 'admin@example.com', 'SAO PAULO',  'SAO PAULO', 'd858de5b-ed02-4c89-ac6a-d899a698d4de', true, CURRENT_TIMESTAMP),
  ('Regular User', 'user@example.com', 'SAO PAULO',  'SAO PAULO', '3292f0cb-cc5d-480e-b5b7-7619e676c8f5', true, CURRENT_TIMESTAMP);

commit;